### ISSUE TITLE
Notice of intention to change licence type from BSD 3 to MIT (Scalm)

### ISSUE THREAD

**Issue by davesmith00000** [PurpleKingdomGames/tyrian#1]
Dear former contributors to [Scalm](https://github.com/julienrf/scalm)!

(According to github, that's: @julienrf, @salc2, and @battermann.)

As mentioned on the Scalm gitter account, I've forked the excellent (but seemingly abandoned) Scalm as I hope to use it in conjunction with [Indigo](https://github.com/PurpleKingdomGames/indigo). I've brought it up to date, converted it to Scala 3, and I've started changing the apis and internals in to suit my own purposes. I do plan to release it (why not?).

The current licence agreement specifically mentions Julien Richard-Foy and EPFL, and I'd like to switch across to an MIT licence and change the named people to be consistent with [Indigo's licence agreement](https://github.com/PurpleKingdomGames/indigo/blob/master/LICENCE.md) and representative of who is looking after this version of the project (the original will remain as-is).

I would appreciate it if you could respond with your approval, or indeed your objections.

I realise most of you haven't looked at Scalm for 3 years or so (which is part of the reason for the fork!) so if I don't hear from you within 30 days, I'll go ahead and assume I have your consent.

Thank you for building the project in the first place!

All the best,

Dave

**Comment by salc2** [comment]
Hi David,
First of all I think it's great you folks have plan to integrate Scalm with
Indigo, I always have thought Elm like architecture applied to games have
lot of potential, really looking forward to seeing this.
About the fork and the licence, besides I know nothing about licences, I
think it's Julien and EPFL decision, I will support any.
I felt I needed to come with a comment because I was mentioned in the
thread but my contribution was really minimal actually, I think Julien's
work in Scalm was really great, neat and polished and I would love to see
more of this project, like ported to Scala 3 and with different views other
than vdom but Canvas or webgl.


Thanks,
Javier.

**Comment by davesmith00000** [comment]
Hi @salc2,

Thanks! When you're moving licence you can only really move with the blessing of all former contributors - however many commits they added. :-)

I agree, lots of potential for games but also this particular architecture is in my opinion, the best one out there for web dev in general, and it really doesn't exist in Scala at the moment.

Indigo use the Elm Architecture specifically for WebGL (2.0) and game development, so my interest in Scalm/Tyrian is mostly Web dev (and games that use web tech) and Canvas. I will probably add WebGL support in places too, but it's not the primary focus as I have Indigo for that.

I've already upgraded to fully Scala 3 now and it makes the syntax even nicer to work with. All the readme examples, and example apps are Scala 3 now if you're interested.

The main use cases I have are for housing Indigo games and building / rebuilding supporting tooling such as simple image editors and game asset conversion tools.

Thank you for your support! :-)

Dave

**Comment by julienrf** [comment]
Hello!

I’m super happy to see that you are interested in this project!

Feel free to change the license to whatever suits you!

**Comment by davesmith00000** [comment]
Hi @julienrf,

Excellent, many thanks! I shall give the final contributor a chance to respond but I really appreciate your endorsement. :-)

All the best,

Dave

**Comment by davesmith00000** [comment]
Thanks all, switched to MIT licence as discussed.
