### ISSUE TITLE
Question: tyrianapp.js Scala version sync

### ISSUE THREAD

**Issue by gvolpe** [PurpleKingdomGames/tyrian#126]
Hi @davesmith00000  👋

Any tips on how to keep the Scala version on the `tyrianapp.js` file up to date whenever Scala Steward updates it? Can it be read from build.sbt or so? I had a look around the Tyrian repo but nothing stands out.

E.g. https://github.com/PurpleKingdomGames/tyrian/blob/main/examples/http/tyrianapp.js#L3

**Comment by armanbilge** [comment]
You can try adding it to the `fileExtensions` in your steward configuration.

https://github.com/scala-steward-org/scala-steward/blob/e94fc77485a2beb9c366015507dcda1393e25cda/docs/repo-specific-configuration.md?plain=1#L62

**Comment by gvolpe** [comment]
Thank you, will try that!
