### ISSUE TITLE
Sourcemap pointing to local directories

### ISSUE THREAD

**Issue by zetashift** [PurpleKingdomGames/tyrian#155]
When using `Vite` and it's dev server, Tyrian sourcemaps seem to have this URL:
```
Error while fetching an original source: can't assign to property "metadata" on "unsupported protocol for sourcemap request file:///home/dave/repos/pkg/tyrian/tyrian-io/src/main/scala/tyrian/TyrianApp.scala": not an object
Source URL: <unknown>
```

That file URL doesn't get loaded, meaning less helpful debugging options. The fix seems to be in a compiler flag that needs to be set for sourcemaps:
For example: https://github.com/typelevel/sbt-typelevel/blob/4da726ca021ea2c6459e8286d9ec49ab7c79a883/github/src/main/scala/org/typelevel/sbt/TypelevelScalaJSGitHubPlugin.scala#L34
Laminar: https://github.com/raquo/Laminar/blob/739cc0dbab319c685f28be30a1592b7d04347842/build.sbt#L76

I'll try to open a PR, if that's okay!

**Comment by davesmith00000** [comment]
@zetashift That would be fantastic if you have the time. If not I'll try and have a go! Thanks for raising the issue. :smile:

**Comment by zetashift** [comment]
I'll pick it up! :D
