### ISSUE TITLE
Feature : 'OnChange' event handler does not transmit parameter (like select value)

### ISSUE THREAD

**Issue by snichele** [PurpleKingdomGames/tyrian#180]
I have a select box, like for example :

```scala
select(onChange(...), option(value:="one"), ...)
```

but the 'onChange' handler does not transmit me the selected option value (at least, not in the current API)...

Endend up doing something like this, which is not pretty :

```scala
select(
      onEvent("change", (e: Tyrian.Event) =>
        val selectValue = e.target.asInstanceOf[HTMLSelectElement].value;
        // ...
      )
    // ...
)
```

Maybe I'm missing something (not so) obvious ? :)

**Comment by davesmith00000** [comment]
PR with the fix is done, I shall merge it in the morning after I've looked it over with fresh eyes. :smile: 

https://github.com/PurpleKingdomGames/tyrian/pull/181
