### ISSUE TITLE
Websocket disconnect not passing WebSocketConnect.Error

### ISSUE THREAD

**Issue by Tvaroh** [PurpleKingdomGames/tyrian#203]
Hey, looks like `WebSocketConnect.Error` is never actually used in the code, so the first branch never happens here:
```scala
WebSocket.connect[F, Msg[F]](apiSocketUrl, KeepAliveSettings.default):
  case WebSocketConnect.Error(_) => ???
  case WebSocketConnect.Socket(ws) => ???
```
I tried to implement automatic reconnect and found this. Also noticed that `WebSocketConnect.Socket(ws)` is indeed called when connection actually gets lost.

**Comment by Tvaroh** [comment]
Actually I was able to implement reconnect by handling `WebSocketEvent.Close`. Still not sure if that `WebSocketConnect.Error` case is ever called thought, but doesn't harm me.

**Comment by armanbilge** [comment]
In practice websocket errors are pretty useless, see:
https://github.com/http4s/http4s-dom/blob/726af7c65e4bf345b66a192bf05c5a28b2fdacd1/dom/src/main/scala/org/http4s/dom/WebSocketClient.scala#L76-L78
