### ISSUE TITLE
Suggestion: ImageLoader improvement

### ISSUE THREAD

**Issue by calvinlfer** [PurpleKingdomGames/tyrian#218]
The [ImageLoader API](https://tyrian.indigoengine.io/guides/goodies/) returns back an `HTMLImageElement` which is part of the scalajs dom. I've been doing the following to convert it to a Tyrian image element:
```scala
val imageFromLoader: HTMLImageElement = ...
img(src := imageFromLoader.source)
```

Is this the right way to go about it? 

I was wondering if `ImageLoader.load` would give you back a Result.Image of a tyrian image element instead of a scalajs dom element so we didn't have to juggle between the two types of elements.

**Comment by davesmith00000** [comment]
Gosh! 6 months, my apologies, I've been busy doing other things... :cold_sweat: 

You are quite right, thank you for reporting this.

I believe I have accidentally / coincidentally addressed this in this PR: https://github.com/PurpleKingdomGames/tyrian/pull/239

These other two issues are related:
https://github.com/PurpleKingdomGames/tyrian/issues/233
https://github.com/PurpleKingdomGames/tyrian/issues/238

**Comment by davesmith00000** [comment]
Merged, will be in the next release.

**Comment by calvinlfer** [comment]
Wooot
