### ISSUE TITLE
HTML input value is not reflected on the view

### ISSUE THREAD

**Issue by gvolpe** [PurpleKingdomGames/tyrian#60]
It seems the `value` attribute of an input field is not correctly reflected on the view when the model changes.

```scala
case class Model(input: String)

input(`type` := "text", attribute("value", model.input))
```

The `input` field is updated either on `Msg.SymbolChanged` or reset (`input = ""`) on `Msg.Subscribe`.

```scala
// view
input(`type` := "text", attribute("value", model.input), onInput(s => Msg.SymbolChanged(s)))

// update
case Msg.SymbolChanged(in) =>
  model.copy(input = in) -> Cmd.Empty

case Msg.Subscribe =>
  val nm  = model.copy(input = "")
  val cmd = model.ws.map(ws => Cmd.Batch(ws.publish(WsIn.Subscribe.asJson.noSpaces), refocusInput))
  nm -> cmd.getOrElse(Cmd.Empty)
```

Everytime the model is updated in the first message, I can see the HTML input value is updated (seeing this by inspecting the element in the browser). However, when the `Subscribe` message is handled and the `input` in the model is reset, the `value` attribute is properly reset as well, but the view remains with the previous value.

Here's an example from the trading application, right after clicking subscribe, where I first noticed the issue.

![issue](https://i.imgur.com/5tgFugk.png)

The `value` attribute is reset but the view still shows the previously entered value "CHFEUR". I'd expect the input field to be cleared up as well.

**Comment by aumann** [comment]
I believe this is something about "attribute" vs "property". Unfortunately, I don't remember the details anymore. However, I solved it by creating a value property and using that:

```
def valueProp(value: String): tyrian.Attr[Nothing] = tyrian.Property("value", value)
```

I completely forgot about this, should have contributed back (at least the question...)

**Comment by davesmith00000** [comment]
Oh that's interesting - thanks for the tip!

**Comment by davesmith00000** [comment]
Morning @gvolpe and @aumann,

I'm having two problems with this:

1. I fully accept the properties vs attributes thing - it's a little confusing but I'm prepared to make the code change. However finding a list of attributes that should be properties is proving tricky.
2. The bigger problems is that I can't replicate it (or I'm miss-understanding the issue and therefore failing to replicate it). Can you give me a hand?

I've been trying to break the "field" example in the tyrian examples folder. To run that example:

`sbt build5` in the `examples` dir of the tyrian repo, then cd `examples/field`, `yarn install` (the first time), `yarn start`.

Here is the change I made:

```diff
diff --git a/examples/field/src/main/scala/example/Main.scala b/examples/field/src/main/scala/example/Main.scala
index 76416e8..4c94470 100644
--- a/examples/field/src/main/scala/example/Main.scala
+++ b/examples/field/src/main/scala/example/Main.scala
@@ -13,6 +13,7 @@ object Main extends TyrianApp[Msg, Model]:
   def update(msg: Msg, model: Model): (Model, Cmd[Msg]) =
     msg match
       case Msg.NewContent(content) => (content, Cmd.Empty)
+      case Msg.Clear => ("", Cmd.Empty)
 
   def view(model: Model): Html[Msg] =
     div()(
@@ -21,6 +22,8 @@ object Main extends TyrianApp[Msg, Model]:
         onInput(s => Msg.NewContent(s)),
         myStyle
       ),
+      input(`type` := "text", attribute("value", "Entered: " + model)),
+      button(onClick(Msg.Clear))("clear"),
       div(myStyle)(text(model.reverse))
     )
 
@@ -39,4 +42,5 @@ object Main extends TyrianApp[Msg, Model]:
 type Model = String
 
 enum Msg:
-  case NewContent(content: String) extends Msg
+  case NewContent(content: String)
+  case Clear
```

That appears to work, and changing `attribute` to `property` seems to make no difference... what am I missing?

> Unrelated: `attribute("value", "Entered: " + model)` is needed here due to a bug, but in the unreleased version `value := "Entered: " + model` is identical.

**Comment by davesmith00000** [comment]
Excellent - thanks @aumann! I can see it _not_ working now.

So that only leaves problem 1 to solve: I can certainly change it for `value` everywhere... but does `value` always need to be a property? And which other attributes/properties does this apply to? 🤔

**Comment by gvolpe** [comment]
We could probably look into what Elm does? I must admit, this is way out of the scope of my knowledge 😄

**Comment by davesmith00000** [comment]
I suspect that secretly, this is really a snabbdom thing.

So plan B is to fix this specific case and wait for more instances of this issue to roll in as people use the library more.

Removing snabbdom is on my wish list of things to do. 🙂

**Comment by davesmith00000** [comment]
https://github.com/elm/html/blob/master/properties-vs-attributes.md
😭

**Comment by aumann** [comment]
For future reference, if there should be more issues, an entry level explanation of attributes vs DOM properties: https://stackoverflow.com/a/6004028/14188171
