### ISSUE TITLE
Add aria-attributes?

### ISSUE THREAD

**Issue by aumann** [PurpleKingdomGames/tyrian#98]
As a follow up to adding SVG tags. See https://github.com/PurpleKingdomGames/tyrian/pull/97#issuecomment-1115244031

At the moment, for me at least, mostly useful when (semi) automatically converting Tailwind templates from html to tyrian.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes

**Comment by davesmith00000** [comment]
Just having another look at this. What we need is a table of names and acceptable types, then the attributes can be generated along with the others... but I'm struggling to find one. MDN usually does the trick but I'm not seeing it this time?

As a first pass, I'm going to generate all of these as string attributes and people can help improve them as they discover problems.
